---

- name: directory dbconfig-common
  file:
    state: directory
    path: /etc/dbconfig-common
    owner: root
    group: root
    mode: 0755

- name: DBconfig for IDO PostgreSQL
  copy:
    dest: /etc/dbconfig-common/icinga2-ido-pgsql.conf
    content: |
      dbc_install='false'
      dbc_upgrade='false'
      dbc_remove='false'
    owner: root
    group: root
    mode: 0600

- name: Apt - install package icinga2-ido-pgsql
  apt:
    name: icinga2-ido-pgsql
    state: present
