- name: Yum - install package icinga2
  yum:
    name: icinga2
    state: present
- name: Yum - install package icinga2-selinux
  yum:
    name: icinga2-selinux
    state: present
  when: ansible_selinux is defined and ansible_selinux.status == "enabled"
