---

- name: feature checker CheckerComponent object
  icinga2_object:
    name: checker
    type: CheckerComponent
    file: features-available/checker.conf
    args: "{{ icinga2_dict_features.checker }}"
  register: result

- set_fact:
    icinga2_local_objects: "{{ icinga2_local_objects|default([]) + [result.dest] }}"
