---

- name: feature graphite GraphiteWriter object
  icinga2_object:
    name: graphite
    type: GraphiteWriter
    file: features-available/graphite.conf
    args: "{{ icinga2_dict_features.graphite }}"
  register: result

- set_fact:
    icinga2_local_objects: "{{ icinga2_local_objects|default([]) + [result.dest] }}"
