---

- name: set api feature facts
  set_fact:
    icinga2_import_schema: "{{ icinga2_dict_features.idomysql.import_schema| default(False) }}"

- name: feature idomysql IdoMysqlConnection object
  icinga2_object:
    name: ido-mysql
    type: IdoMysqlConnection
    file: features-available/ido-mysql.conf
    args: "{{ icinga2_dict_features.idomysql }}"
  register: result

- set_fact:
    icinga2_local_objects: "{{ icinga2_local_objects|default([]) + [result.dest] }}"

- name: install on {{ ansible_os_family }}
  include_tasks: "features/idomysql/install_on_{{ ansible_os_family }}.yml"

- name: MySQL import IDO schema
  block:
    - name: build mysql command
      set_fact:
        mysqlcmd: >-
          mysql {% if icinga2_dict_features.idomysql.host| default('localhost') != 'localhost'  %} -h "{{ icinga2_dict_features.idomysql.host }}" {%- endif %}
          {% if icinga2_dict_features.idomysql.port is defined %} -P "{{ icinga2_dict_features.idomysql.port }}" {%- endif %}
          -u "{{ icinga2_dict_features.idomysql.user |default('icinga2') }}"
          -p"{{ icinga2_dict_features.idomysql.password }}"
          "{{ icinga2_dict_features.idomysql.database |default('icinga2') }}"

    - name: MySQL check for IDO schema
      shell: >
        {{ mysqlcmd }}
        -Ns -e "select version from icinga_dbversion"
      failed_when: false
      changed_when: false
      check_mode: false
      register: db_schema

    - name: MySQL import IDO schema
      shell: >
        {{ mysqlcmd }}
        < /usr/share/icinga2-ido-mysql/schema/mysql.sql
      when: db_schema.rc != 0
  when: icinga2_dict_features.idomysql.import_schema| default(False)

- set_fact:
    args: None
