---

- name: feature influxdb InfluxdbWriter object
  icinga2_object:
    name: influxdb
    type: InfluxdbWriter
    file: features-available/influxdb.conf
    args: "{{ icinga2_dict_features.influxdb }}"
  register: result

- set_fact:
    icinga2_local_objects: "{{ icinga2_local_objects|default([]) + [result.dest] }}"
